const fs = require('fs');

const extraSights = `

export const extraSights: ItineraryItem[] = [
  {
    id: 'e1',
    day: null,
    title: 'Palast von Phaistos',
    subtitle: 'Ausgrabungsstätte',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Phaistos_view_of_the_ruins.jpg?width=800',
    bestTime: 'Vormittags oder Spätnachmittag',
    location: 'Phaistos',
    lat: 35.0514,
    lng: 24.8143,
    plan: 'Die zweitgrößte minoische Palastanlage auf Kreta. Weniger überlaufen als Knossos und mit fantastischem Blick über die Messara-Ebene.',
    tavernaTip: { name: 'Taverna Agios Ioannis', rating: '4,6/5', desc: 'Fantastischer Blick und traditionelles Essen' },
    budget: 20,
    budgetDesc: '(Eintritt 8€ pro Person)',
    navLink: 'https://www.google.com/maps/dir/Matala,+Griechenland/Phaistos,+Griechenland',
    isOptional: true,
    costId: 'e1',
  },
  {
    id: 'e2',
    day: null,
    title: 'Gortyn',
    subtitle: 'Römische Ruinenstadt',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Gortyna_Odeion.jpg?width=800',
    bestTime: 'Vormittags',
    location: 'Gortyna',
    lat: 35.0624,
    lng: 24.9472,
    plan: 'Ehemalige römische Hauptstadt von Kreta mit dem berühmten Stadtrecht (Gesetzestexte in Stein gemeißelt).',
    tavernaTip: { name: 'Taverna in Agioi Deka', rating: '4,5/5', desc: 'Einfache Tavernen im Nachbardorf' },
    budget: 20,
    budgetDesc: '(Eintritt 6€ pro Person)',
    navLink: 'https://www.google.com/maps/dir/Matala,+Griechenland/Gortyna,+Griechenland',
    isOptional: true,
    costId: 'e2',
  },
  {
    id: 'e3',
    day: null,
    title: 'Melidoni Höhle',
    subtitle: 'Historische Tropfsteinhöhle',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Melidoni_cave.jpg?width=800',
    bestTime: 'Mittags als Abkühlung',
    location: 'Melidoni',
    lat: 35.3850,
    lng: 24.7350,
    plan: 'Eine der historisch bedeutendsten und schönsten Tropfsteinhöhlen Kretas.',
    tavernaTip: { name: 'Carnivore in Melidoni', rating: '4,7/5', desc: 'Perfekt für Fleischliebhaber' },
    budget: 15,
    budgetDesc: '(Eintritt 4€ pro Person)',
    navLink: 'https://www.google.com/maps/dir/Matala,+Griechenland/Melidoni+Cave,+Griechenland',
    isOptional: true,
    costId: 'e3',
  },
  {
    id: 'e4',
    day: null,
    title: 'Imbros Schlucht',
    subtitle: 'Tolle Wanderung',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Imbros_Gorge.jpg?width=800',
    bestTime: 'Morgens',
    location: 'Imbros',
    lat: 35.2415,
    lng: 24.1681,
    plan: 'Die perfekte, etwas kürzere und einfachere Alternative zur Samaria Schlucht.',
    tavernaTip: { name: 'Taverna Porofarango', rating: '4,6/5', desc: 'Direkt am Einstieg der Schlucht' },
    budget: 20,
    budgetDesc: '(Eintritt 2,50€, Rücktransport per Taxi ca. 5€ p.P.)',
    navLink: 'https://www.google.com/maps/dir/Matala,+Griechenland/Imbros+Gorge,+Griechenland',
    isOptional: true,
    costId: 'e4',
  },
  {
    id: 'e5',
    day: null,
    title: 'Antikes Aptera',
    subtitle: 'Ruinen über der Souda Bucht',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Aptera_Cisterns_01.jpg?width=800',
    bestTime: 'Später Nachmittag',
    location: 'Aptera',
    lat: 35.4627,
    lng: 24.1408,
    plan: 'Riesige römische Zisternen, ein Theater und türkische Festungen mit grandioser Aussicht auf die Souda-Bucht.',
    tavernaTip: { name: 'Taverna Aptera', rating: '4,8/5', desc: 'Urige Taverne im nahegelegenen Dorf' },
    budget: 15,
    budgetDesc: '(Eintritt 4€ pro Person)',
    navLink: 'https://www.google.com/maps/dir/Matala,+Griechenland/Aptera,+Griechenland',
    isOptional: true,
    costId: 'e5',
  }
];
`;

fs.appendFileSync('./src/data/itinerary.ts', extraSights);
console.log('Appended extraSights to itinerary.ts');
